"""
QMIX baseline (value-decomposition MARL).

Learns a joint action-value function Q_tot that factorizes into per-agent
utilities Q_i via a **mixing network** whose weights are generated by a
hypernetwork from the global state. Training is centralised (the mixer sees the
true global state); execution is fully decentralised -- each agent greedily
argmaxes its own Q_i, which is the property that makes QMIX a strong discrete
cooperative baseline.

Implemented as a double-Q TD update from a replay buffer:
  target = r + gamma * Q_tot_target(s', argmax_{a'} Q_i_cur(s'))  (double Q)
  loss   = (Q_tot(s, a) - target)^2
where Q_tot = Mixer([Q_1(a_1), ..., Q_n(a_n)] | global_state).

The QMIX monotonicity guarantee (improving one agent's utility never lowers the
joint value) is enforced by clamping the mixing weights non-negative (softplus).
"""

import numpy as np
from .mlp import MLP, Adam, softmax, one_hot


class MixingNetwork:
    """Q_tot = W2^T * ReLU(W1 u + b1) + b2, where W1, b1, W2, b2 are all
    produced by a hypernetwork from the global state (the concatenation of every
    agent's own-state features). Weights are softplus-clamped for monotonicity.
    Exposes a vectorised forward and an exact backward (analytic chain rule)."""

    def __init__(self, n_agents, hidden, state_dim, rng):
        self.n_agents = n_agents
        self.hidden = hidden
        out = hidden * n_agents + hidden + hidden + 1
        self.hyper = MLP([state_dim, hidden, out], rng)

    def param_refs(self):
        return self.hyper.param_refs()

    def _split(self, h):
        """h: (B, hyper_out) -> (W1, b1, W2, b2) where W1/W2 are the
        softplus-clamped (monotone) mixing weights."""
        n = self.n_agents
        hd = self.hidden
        off = 0
        W1 = h[:, off:off + hd * n].reshape(-1, hd, n); off += hd * n
        b1 = h[:, off:off + hd]; off += hd
        W2 = h[:, off:off + hd]; off += hd
        b2 = h[:, off:off + 1][:, 0]
        W1 = np.log1p(np.exp(np.clip(W1, -30, 30)))
        W2 = np.log1p(np.exp(np.clip(W2, -30, 30)))
        return W1, b1, W2, b2

    def forward_tensor(self, u, states):
        """u: (B, n_agents) chosen per-agent utilities -> Q_tot (B,)."""
        h = self.hyper.forward(states)
        W1, b1, W2, b2 = self._split(h)
        z = np.maximum(0.0, np.einsum("bhk,bk->bh", W1, u) + b1)
        return np.einsum("bh,bh->b", W2, z) + b2

    def forward(self, u, state):
        return float(self.forward_tensor(u[None, :], state[None, :])[0])

    def backward_tensor(self, u, states, dqtot):
        """Given dL/dQ_tot (B,), return (du, dhyper) with du (B, n_agents) and
        dhyper (B, hyper_out) via exact chain rule through the clamped mixer."""
        B = states.shape[0]
        n = self.n_agents
        hd = self.hidden
        h = self.hyper.forward(states)

        # raw (pre-softplus) hyper outputs, clipped exactly as in _split
        off = 0
        W1_raw = h[:, off:off + hd * n].reshape(-1, hd, n); off += hd * n
        b1 = h[:, off:off + hd]; off += hd
        W2_raw = h[:, off:off + hd]; off += hd
        b2 = h[:, off:off + 1][:, 0]
        W1 = np.log1p(np.exp(np.clip(W1_raw, -30, 30)))
        W2 = np.log1p(np.exp(np.clip(W2_raw, -30, 30)))
        W1c, W2c = np.clip(W1_raw, -30, 30), np.clip(W2_raw, -30, 30)
        sig_W1 = 1.0 / (1.0 + np.exp(-W1c))   # d(softplus)/d(raw)
        sig_W2 = 1.0 / (1.0 + np.exp(-W2c))

        z = np.maximum(0.0, np.einsum("bhk,bk->bh", W1, u) + b1)
        gz = (z > 0.0).astype(np.float64)

        # dL/dz_lin (post-relu gate): Q_tot = sum_h W2_h z_h + b2
        dldz = dqtot[:, None] * gz * W2                        # (B, h)

        # dL/du = W1^T dL/dz_lin
        du = np.einsum("bh,bhk->bk", dldz, W1)                # (B, n)

        # dL/dW1_s[h,k] = dL/dz_lin[h] * u[k];  dL/db1 = dL/dz_lin
        dW1_s = np.einsum("bh,bk->bhk", dldz, u)              # (B, h, n)
        dW1_raw = dW1_s * sig_W1
        db1 = dldz                                            # (B, h)

        # dL/dW2_s[h] = dqtot[h] * z[h]
        dW2_s = dqtot[:, None] * z                            # (B, h)
        dW2_raw = dW2_s * sig_W2
        db2 = dqtot                                           # (B,)

        dhyper = np.zeros_like(h)
        off = 0
        dhyper[:, off:off + hd * n] = dW1_raw.reshape(B, hd * n); off += hd * n
        dhyper[:, off:off + hd] = db1; off += hd
        dhyper[:, off:off + hd] = dW2_raw; off += hd
        dhyper[:, off:off + 1] = db2[:, None]
        return du, dhyper


class QMIX:
    def __init__(self, obs_dim, n_actions, n_agents, state_dim, hidden=64,
                 mix_hidden=32, lr=3e-4, gamma=0.99, rng=None, seed=0,
                 target_update_every=200):
        rng = rng or np.random.default_rng(seed)
        self.n_agents = n_agents
        self.n_actions = n_actions
        self.obs_dim = obs_dim
        self.state_dim = state_dim
        self.gamma = gamma
        self.target_update_every = target_update_every
        self.updates = 0

        # per-agent Q-network: one shared MLP applied to every agent's obs
        self.qnet = MLP([obs_dim, hidden, hidden, n_actions], rng)
        self.qnet_target = MLP([obs_dim, hidden, hidden, n_actions], rng)
        self._copy_params(self.qnet_target, self.qnet)

        self.mix = MixingNetwork(n_agents, mix_hidden, state_dim, rng)
        self.opt = Adam(self.qnet.param_refs() + self.mix.param_refs(), lr=lr)

    @staticmethod
    def _copy_params(dst, src):
        for (d, _), (s, _) in zip(dst.param_refs(), src.param_refs()):
            d[...] = s

    def _hard_update(self):
        """Periodic full copy of the online net into the target net."""
        self._copy_params(self.qnet_target, self.qnet)

    # ------------------------------------------------------------------ act
    def act(self, obs, mask, greedy=True):
        """obs: (n, obs_dim), mask: (n, n_actions). Decentralised greedy."""
        q = self.qnet.forward(obs) + np.where(mask > 0.5, 0.0, -1e9)
        return np.argmax(q, axis=1)


def build_state(env):
    """Global state used by the mixer: concatenated own-state features (3D).
    x/y are normalized by area_size, z by altitude_max, so the hypernetwork
    input is O(1)."""
    per = np.stack([env.pos[:, 0] / env.cfg.area_size,
                    env.pos[:, 1] / env.cfg.area_size,
                    env.pos[:, 2] / env.cfg.altitude_max,
                    env.soc,
                    env.stranded.astype(np.float64)], axis=-1)
    return per.flatten()


def qmix_bc_warmstart(qmix, obs, acts, mask, iters, rng, batch=128):
    """Behavior-clone the utility network onto demonstrated (greedy-style)
    actions so argmax_q(s, .) matches the demo choices before any TD bootstrap
    runs -- the same warm-start recipe the MAPPO baseline uses in this project.
    obs: (T, n, obs_dim) transitions (flattened internally)."""
    if obs.ndim == 3:
        obs = obs.reshape(-1, obs.shape[-1])
        acts = acts.reshape(-1)
        mask = mask.reshape(-1, mask.shape[-1])
    n = obs.shape[0]
    A = qmix.n_actions
    losses = []
    for _ in range(iters):
        idx = rng.integers(0, n, size=batch)
        logits = qmix.qnet.forward(obs[idx]) + np.where(mask[idx] > 0.5, 0.0, -1e9)
        probs = softmax(logits)
        logp = np.log(np.clip(probs[np.arange(batch), acts[idx]], 1e-12, 1.0))
        losses.append(-float(np.mean(logp)))
        dlogits = (probs - one_hot(acts[idx], A)) / batch
        dlogits = dlogits * mask[idx]
        _, grads = qmix.qnet.backward(dlogits)
        g = []
        for name in [nm for _, nm in qmix.qnet.param_refs()]:
            gg = grads[name[:-2]]
            g.append(gg["W"] if name.endswith("W") else gg["b"])
        qmix.opt.step(g)
    return losses


def qmix_update(qmix, batch, batch_size, rng, q_lim=5000.0, bc_weight=0.0):
    """One double-Q TD update from a replay batch.

    batch: (obs, acts, rews, next_obs, dones, states, next_states)
      obs/next_obs: (B, n, obs_dim), acts (B, n), rews (B, n),
      dones (B,), states/next_states (B, state_dim).
    Returns a stats dict."""
    obs, acts, rews, next_obs, mask, next_mask, dones, states, next_states = batch
    B, n, d = obs.shape
    A = qmix.n_actions

    # double Q: greedy next actions from *current* qnet, evaluated by target.
    # Invalid (padded) next actions are masked out so their drifting utilities
    # cannot leak into the bootstrapped target.
    next_q_cur = qmix.qnet.forward(next_obs.reshape(B * n, d)).reshape(B, n, A)
    next_q_cur = next_q_cur + np.where(next_mask > 0.5, 0.0, -1e9)
    next_act = np.argmax(next_q_cur, axis=2)                      # (B, n)
    u_next = qmix.qnet_target.forward(next_obs.reshape(B * n, d)).reshape(B, n, A)
    chosen_next = u_next[np.arange(B)[:, None], np.arange(n), next_act]
    qtot_next = qmix.mix.forward_tensor(chosen_next, next_states)   # (B,)
    target = rews.mean(axis=1) + qmix.gamma * (1.0 - dones) * qtot_next
    target = np.clip(target, -q_lim, q_lim)   # bootstrap stability clamp

    u = qmix.qnet.forward(obs.reshape(B * n, d)).reshape(B, n, A)
    chosen = u[np.arange(B)[:, None], np.arange(n), acts]           # (B, n)
    qtot = qmix.mix.forward_tensor(chosen, states)
    td = qtot - target
    loss = float(np.mean(td ** 2))

    dqtot = 2.0 * td / B
    du, dhyper = qmix.mix.backward_tensor(chosen, states, dqtot)
    dhyper = np.clip(dhyper, -20.0, 20.0)   # stability for the hypernetwork
    dqnet = np.zeros((B, n, A))
    dqnet[np.arange(B)[:, None], np.arange(n), acts] = du

    # Optional behavior-cloning regularization: keeps the utility ordering
    # anchored to the demonstrated (greedy-style) task choices, which stops the
    # offline bootstrap from drifting the unobserved HOLD utility above every
    # task utility (a known instability of offline Q-learning on near-
    # deterministic buffers -- same idea as the MAPPO warm-start in this repo).
    if bc_weight > 0.0:
        logits = qmix.qnet.forward(obs.reshape(B * n, d)).reshape(B, n, A)
        logits = logits + np.where(mask > 0.5, 0.0, -1e9)
        probs = softmax(logits.reshape(B * n, A)).reshape(B, n, A)
        logp = np.log(np.clip(probs[np.arange(B)[:, None], np.arange(n), acts],
                              1e-12, 1.0))
        bc_loss = float(-np.mean(logp))
        dlogits = probs - one_hot(acts.reshape(B * n), A).reshape(B, n, A)
        dqnet = dqnet + bc_weight * dlogits / (B * n)
    else:
        bc_loss = 0.0

    _, qnet_grads = qmix.qnet.backward(dqnet.reshape(B * n, A))
    _, hyper_grads = qmix.mix.hyper.backward(dhyper)

    grads = []
    for name in [nm for _, nm in qmix.qnet.param_refs()]:
        g = qnet_grads[name[:-2]]
        grads.append(g["W"] if name.endswith("W") else g["b"])
    for name in [nm for _, nm in qmix.mix.hyper.param_refs()]:
        g = hyper_grads[name[:-2]]
        grads.append(g["W"] if name.endswith("W") else g["b"])
    qmix.opt.step(grads)
    qmix.updates += 1
    if qmix.updates % qmix.target_update_every == 0:
        qmix._hard_update()

    return {"td_loss": loss, "mean_q_tot": float(qtot.mean()),
            "mean_target": float(target.mean()), "bc_loss": bc_loss}
